# Site settings
title: Recursive
email: info@arrowtype.com
author: Arrow Type
description: Recursive is a variable font for code & UI
url: https://recursive.design

# Build settings
permalink: :title/
sass:
  sass_dir: css
